#!/bin/bash
source /opt/ros/kinetic/setup.bash
source /home/xbot/catkin_ws/devel/setup.bash
case "$1" in
	start)
		/usr/local/nginx/sbin/nginx
		roslaunch xbot_bringup xbot.launch
		;;
	stop)
		;;
	restart)
		;;
esac

		
